export enum InputTypes {
  text = 'text',
  button = 'button',
  checkbox = 'checkbox',
  color = 'color',
  date = 'date',
  datetimeLocal = 'datetime-local',
  email = 'email',
  file = 'file',
  hidden = 'hidden',
  image = 'image',
  month = 'month',
  number = 'number',
  password = 'password',
  radio = 'radio',
  range = 'range',
  search = 'search',
  submit = 'submit',
  tel = 'tel',
  time = 'time',
  url = 'url',
  week = 'week',

  select = 'select',
}
